### ISSUE TITLE
Not working for PDFs in Safari

### ISSUE THREAD

**Issue by jannis-baum** [godbout/Scrolla.docs#1]
While viewing a PDF in Safari, Scrolla doesn't find the main area to scroll the PDF

**Comment by godbout** [comment]
reference for myself: https://www.macalester.edu/studentaccounts/wp-content/uploads/sites/44/2015/01/2014ViewingPDFsinAppleSafari.pdf

**Comment by godbout** [comment]
alpha 2

https://user-images.githubusercontent.com/121373/203589468-0bb9e991-7792-43bd-bfd6-3a398af624b1.mp4

**Comment by godbout** [comment]
you'll notice the habit of starting kV to scroll 🤣️

**Comment by godbout** [comment]
i think i have something better for a2: if no scroll areas is found, then Scrolla highlight the whole app. then you can scroll. will help with web browsers and shit Electron apps. if scroll areas are found, then Scrolla doesn't highlight the whole app, as this will mostly be redundant.

**Comment by godbout** [comment]
incidentally this will take care of #3 as there will always be a Target.

**Comment by godbout** [comment]
will be working now, at least if the PDF takes the entire page: https://github.com/godbout/Scrolla.docs/releases/tag/1.a2

please close if ok for now!
