### ISSUE TITLE
Any reason to not scroll with up/down?

### ISSUE THREAD

**Issue by caffo** [godbout/Scrolla.docs#14]
That's about it :)

**Comment by godbout** [comment]
my friend, it's been a while! coincidently enough i was perusing through your lovely site and content yesterday.

the idea was to make scrolling convenient through the Vim motions available on the home row, but yeah, up/down are even actually valid Vim motions. i'll add them (and maybe a few other more). thank you!

**Comment by godbout** [comment]
oh but wait. was starting playing with this, but `up` and `down` are actually already used to pick up a Scroll Area 🤔️

**Comment by godbout** [comment]
we could do something like if there's only one Scroll Area then you can use `up/down` to scroll but that would be quite bad UX i think. inconsistent.

**Comment by caffo** [comment]
Maybe changing `ctrl` `up / down` to select the scroll area? :)

**Comment by godbout** [comment]
> Maybe changing `ctrl` `up / down` to select the scroll area? :)

but that's not macOS standard, right? the current ways to select a Scroll Area are the macOS standard ones: https://github.com/godbout/Scrolla.docs#navigate tab/shift tab, control p/n, up/down. 

the up/down also is consistent with Wooshy. in Wooshy you can use up/down to select the Target. so i did the same for Scrolla. so yeah, hmm, not sure what's the best here. removing up/down to choose Scroll Area will surely break the UX for a bunch of people.

**Comment by caffo** [comment]
You are totally right. I will use the homerow :)

On February 8, 2023, GitHub ***@***.***> wrote:
> > Maybe changing ctrl up / down to select the scroll area? :)
> >
>
> but that's not macOS standard, right? the current ways to select a
> Scroll Area are the macOS standard ones:
> <https://github.com/godbout/Scrolla.docs#navigate> tab/shift tab,
> control p/n, up/down.
>
> the up/down also is consistent with Wooshy. in Wooshy you can use
> up/down to select the Target. so i did the same for Scrolla. so yeah,
> hmm, not sure what's the best here. removing up/down to choose Scroll
> Area will surely break the UX for a bunch of people.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/godbout/Scrolla.docs/issues/14#issuecomment-
1422037206>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAADSH6HAGI5JISVCLOUZTWWMVG3ANCNFSM6AAAAAAUTIHTDA>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by godbout** [comment]
alright. will close for now. please reopen if you think of something that may work.
