### ISSUE TITLE
not working on Arc

### ISSUE THREAD

**Issue by lilyspad** [godbout/Scrolla.docs#15]
While I am able to scroll through the sidebar, I am unable to highlight any fields on actual websites to scroll on.

**Comment by godbout** [comment]
can you share a screencast? which site? works fine here:

https://user-images.githubusercontent.com/121373/218383539-e62e577a-3bed-4db8-976d-5620eef8361f.mp4

so it's possible it's about the site(s) you're dealing with? also usually sites don't have Scroll Areas defined, so Scrolla scrolls the whole browser somehow.

**Comment by cumanzor** [comment]
Can't activate Scrolla while recording with Quicktime Player, oddly enough, but I'm having the same issue across al sites. It seems Scrolla can focus in the sidebar and scroll just fine there (even left and right which is really useful), but I can't focus on the web page itself either.

**Comment by godbout** [comment]
like shown above, it works on my side. so as long as i don't have screencasts, and your Arc Settings, nothing much i can do.

**Comment by cumanzor** [comment]
Video attached. Anything in specific you'd like to see in the settings? I've kept the defaults for everything in arc.

https://user-images.githubusercontent.com/587075/227425319-542eb441-80e1-47da-83b1-f995e9bac88a.mov

**Comment by godbout** [comment]
interesting, i don't seem to have the same UI. is this v0.94?

**Comment by cumanzor** [comment]
It's 0.95.0, updated this afternoon I think.

<img width="396" alt="Screenshot 2023-03-23 at 22 58 35" src="https://user-images.githubusercontent.com/587075/227428482-4a4c3f3b-5098-493a-a1d2-59c3e497beb5.png">

**Comment by godbout** [comment]
alright, thanks. will check and come back to you.

**Comment by godbout** [comment]
hmm. updated to 0.95. all default settings. and in my case the scroll area is the whole browser...

**Comment by cumanzor** [comment]
Yeah just tried on another machine and it's working fine. I wonder if there's another app conflicting here :(. Anyway thanks for taking a look.

**Comment by godbout** [comment]
> Yeah just tried on another machine and it's working fine. I wonder if there's another app conflicting here :(. Anyway thanks for taking a look.

if you find anything please let me know. i still wanna go to the bottom of this and find what's happening. thanks.

**Comment by godbout** [comment]
@cumanzor actually that would be very helpful if you could record what the `Accessibility Inspector` shows on the Arc that fails. point to the two areas that Scrolla detects, so that i can see if it's `ScrollArea` Elements in your case. see video below. thanks.

https://user-images.githubusercontent.com/121373/227697101-67a0a027-3221-4d43-ae62-b44a961c58f5.mp4

**Comment by godbout** [comment]
ok, also maybe try that middle option in Scrolla's Settings. it's actually probably the issue 😅️

<img width="564" alt="Screenshot 2023-03-25 at 13 01 27" src="https://user-images.githubusercontent.com/121373/227697285-0ce0a5a8-11f5-4b29-8a4a-173c600d28ee.png">

**Comment by cumanzor** [comment]
Ahh, that does it! I do lose scrolling on the sidebar but this is better than not being able to scroll through websites. Thanks!!

**Comment by godbout** [comment]
> Ahh, that does it! I do lose scrolling on the sidebar but this is better than not being able to scroll through websites. Thanks!!

yeah by definition web pages (and Electron apps) are tricky coz they're not native so no Scroll Areas. for web browsers the best is definitely to catch the whole app, to scroll the page. but yeah, you lose the Arc UI in Arc's case.
