### ISSUE TITLE
Menubar icon hard to see

### ISSUE THREAD

**Issue by jannis-baum** [godbout/Scrolla.docs#2]
Could consider inverting/adding a background similar to kV's logo

**Comment by godbout** [comment]
this is what i have here:

![Screenshot 2022-11-24 at 00 34 56](https://user-images.githubusercontent.com/121373/203599967-39ea7b80-5868-41ae-86f7-89a82e5944da.png)

seems pretty ok. wondering what you have on your side.

**Comment by jannis-baum** [comment]
Mine is visible of course

![image](https://user-images.githubusercontent.com/85999315/203645028-5918a08f-b4a7-4e38-bded-aca68dabd943.png)

I just feel like it's a little hard to see because the Menubar is already very small, especially on big screens that are a bit further away. It's a subjective thing. Feel free to close if you don't think it's an issue!☺️

**Comment by godbout** [comment]
new icon in a2: https://github.com/godbout/Scrolla.docs/releases/tag/1.a2

still the same idea tho. looks like two fingers scroll. lemme know if this is still too subtle. thanks!
