### ISSUE TITLE
Seems to get the main window scroll only

### ISSUE THREAD

**Issue by anguila** [godbout/Scrolla.docs#20]
Hi,
First, thanks for putting this app together!

I'm facing an issue that in`Ventura 13.2.1` it seems to be picking up only the main window. I tried with tab, up/down and CTRL n, but nothing. It seems just to be able to control the scroll of the main window.

![image](https://github.com/godbout/Scrolla.docs/assets/6177590/d257e954-4a19-40c2-87b6-f6a5d9ee02e5)

Best,

David

**Comment by godbout** [comment]
that's gonna be the case for browsers yes, and probably Electron apps. Scrolla detects `Scrollbars` and `Scroll Areas`. those are properly defined in native apps. for Electron apps and browsers, it's just custom UI rendering shits. "looks" ok, but in terms of structure and accessibility it's shit. lazy stuff. so in those cases Scrolla can only grab the main window, as you're seeing.

for native apps there's an option in Scrolla's Settings:

<img width="564" alt="Screenshot 2023-06-06 at 13 07 30" src="https://github.com/godbout/Scrolla.docs/assets/121373/c00cf60a-24cc-43b4-adcc-59ee1bf07cef">

in some apps like Arc that will help grab the web content, but it's still pretty poor.

**Comment by anguila** [comment]
Ok, thanks for letting me know.
That's a shame because vscode is also an electron app and I'd have loved to use this there... 😢

**Comment by godbout** [comment]
i'll have a look if there's something to do, but i don't think so. i'll keep you updated.

there's some stuff i'm investigating. like moving the cursor around through Vim moves once you've activated Scrolla. currently, Scrolla puts the cursor in the middle of the scrolling area, but actually Scrolla works on what's under the cursor. so in VSCode for example, if you activate Scrolla, then move the cursor let's say with the trackpad, you can still use `jk` etc. wherever you want. of course it's dumb coz you need to move the cursor manually currently. this is where moving the cursor through Vim moves idea comes. but haven't done a prototype yet.

**Comment by godbout** [comment]
> Ok, thanks for letting me know.
> That's a shame because vscode is also an electron app and I'd have loved to use this there... 😢

ok, investigation done. so yeah, VSCode is just a bunch of "Group" UI Element. very lazy Accessibility, but that's Electron. 

out of curiosity, where did you need Scrolla in VSCode? Terminal?

**Comment by anguila** [comment]
Thanks for checking, I appreciate the effort 💪 
Code navigation with a vertical split window, so I can scroll up/down the code. Also, folder navigation on the left and terminal (I split them vertically having 2 of them too)

**Comment by godbout** [comment]
can't do more on this so closing.

**Comment by godbout** [comment]
can also refer to this issue, as the current issue is targeted to Electron apps: https://github.com/godbout/Scrolla.docs/issues/16
