### ISSUE TITLE
Not compatible with BetterMouse very well.

### ISSUE THREAD

**Issue by danny-su** [godbout/Scrolla.docs#21]
I installed BetterMouse and enabled Smooth Scroll, when I use Scrolla to scroll windows, j and k will up or down a lot not a bit.

**Comment by godbout** [comment]
i'll check but if you use other tools that also modify scrolling parameters then yeah, they're gonna affect any other tools, not just Scrolla.

**Comment by danny-su** [comment]
@godbout I want some options to tune the scrolling parameters of Scrolla.

**Comment by godbout** [comment]
lol ok fair. thanks.

**Comment by godbout** [comment]
adding 5 speed options in Scrolla 10.

**Comment by godbout** [comment]
current one, two slower, two faster.

**Comment by godbout** [comment]
done in 10: https://github.com/godbout/Scrolla.docs/releases/tag/10
