### ISSUE TITLE
URI controls

### ISSUE THREAD

**Issue by jannis-baum** [godbout/Scrolla.docs#22]
Same as [Wooshy](https://github.com/godbout/Wooshy.docs/issues/133) & [kV](https://github.com/godbout/kindaVim.docs/issues/200)😇 Here I don't have any fancy ideas for what else URIs could do, I think just `open`, `close` & `toggle` would be good!

**Comment by godbout** [comment]
done in https://github.com/godbout/Scrolla.docs/releases/tag/8
