### ISSUE TITLE
Scrolla crashes when used on Microsoft Outlook

### ISSUE THREAD

**Issue by TaylorFinklea** [godbout/Scrolla.docs#23]
## Steps to reproduce:
1. Open Scrolla
2. Open Outlook
3. Enter shortcut for Scrolla while focused on Outlook

## Expected result
Scrolla is activated for Outlook

## Actual result
Scrolla crashes

## Info
OS Version: macOS Sonoma 14.2.1
Scrolla Version: 14
Microsoft Outlook Version 16.84

I do not recall ever using Scrolla successfully in the past with Outlook, so I'm not sure if this worked in the past

https://github.com/godbout/Scrolla.docs/assets/6810234/2d211b03-b018-43b7-bc3b-ac66ce3f41ca

**Comment by godbout** [comment]
hmm. i remember fixing some crash about an AX Element being set as its own child and parent in one of Microsoft's app 🤣️🤣️🤣️

will check asap. thanks for the report.

**Comment by godbout** [comment]
confirmed. some incest stuff going on at Microsoft. will fix asap.

**Comment by godbout** [comment]
done in https://github.com/godbout/Scrolla.docs/releases/tag/15

enjoy.

**Comment by TaylorFinklea** [comment]
works perfectly now, thank you!
