### ISSUE TITLE
Feedback when no scroll areas were found

### ISSUE THREAD

**Issue by jannis-baum** [godbout/Scrolla.docs#3]
Right now, the focus changes to Scrolla and back for a split second (which makes the active app flicker) when trying to *scrolla* when there are no scroll areas. It might be hard to realize what's going here on for some people. Could consider adding a little popup that stays for a second or so saying there are no scroll areas.

**Comment by godbout** [comment]
mostly it shouldn't happen anymore, as Sl is always going to grab at least the main window: https://github.com/godbout/Scrolla.docs/releases/tag/1.a2

BUT. there's cases where there's a window but it's not visible. so it's a little tricky. i consider this as an issue, will report and link here. not sure yet how to handle those cases then. screen flashing? popup? doing nothing?

**Comment by jannis-baum** [comment]
> BUT. there's cases where there's a window but it's not visible. so it's a little tricky. i consider this as an issue, will report and link here. not sure yet how to handle those cases then. screen flashing? popup? doing nothing?

Not sure if that's already included in what you meant but there's also the case where an app is activated that doesn't have any windows.

**Comment by godbout** [comment]
yeah my bad, i meant exactly what you wrote.

so yeah, i'm able to handle that now. so we're back to giving a feedback when no scroll areas are found... still not really sure whether it should be the user to "understand" there's no window, or if Scrolla should explicitly make it obvious. even more now that if a (visible) window has no scroll area, Scrolla will highlight the window itself.

not saying no. still looking for/digesting the argumentation :D

**Comment by godbout** [comment]
what about using the HazeOver window? the window that shows up behind others in kV? or actually on top of others when an app is in fullscreen. i could make that window flash.

**Comment by godbout** [comment]
this is what i have in mind:


https://user-images.githubusercontent.com/121373/203967289-9b903b21-b46f-4f5b-a900-f36a7362b25b.mp4

**Comment by godbout** [comment]
> * Might be too flashy for some people?

it's fabulous!

> * Looks a bit like a screenshot. Or the opposite of one🙈

indeed. it takes a shot of your face and sends it to me by email 🙈️

> * Doesn't necessarily remind me of Scrolla because it doesn't use this HazeOver in other places does it?

there's gonna be a new option for background/HazeOver window. but yes, i see your point. maybe the border thing may be better.

> So with those in mind, maybe flashing the selection border on the whole screen instead of the HazeOver could be another option? On top of that, I feel like if Apple made this, they would also play this super annoying sound that they play whenever something doesn't work😂 I can't really find anywhere my computer does it right now (maybe (hopefully) there is a way to disable it and that's what I have) but I hope you know which one I mean😁

i know what you mean but i'm gonna avoid this. imagine you're listening to music (i do all the time) and you get this annoying "boing"? huh huh. let's see about the Accessibility issue later. maybe Scrolla will actually not be as useful as Wooshy on this area.

what i can say is that the flash happens exactly when you trigger the hotkey, so it's pretty clear you're/Scrolla is responsible for that. i'll shit a3 with this first and see how it feels over time. i'm afraid drawing the border, even faster, may actually be more confusing, coz you do have the borders over the whole screen sometimes, when Scrolla is dealing with Finder/the Desktop.

**Comment by godbout** [comment]
done in a3: https://github.com/godbout/Scrolla.docs/releases/tag/1.a3

see how it feels with usage.
