### ISSUE TITLE
Distributed Notifications API

### ISSUE THREAD

**Issue by jannis-baum** [godbout/Scrolla.docs#8]
🙈

---

**My concrete use-case:** I have a Karabiner binding to switch tabs. Since switching tabs is `ctrl+tab`, passthrough in kV's Normal mode doesn't work. So I use kV's DN API to keep track of the current mode and when I am in Normal mode, the binding first goes to insert mode, then switches tabs, and finally goes back to Normal mode. This way I can switch tabs with my usual binding "without exiting" kV. I would like to do the same thing with Scrolla.

**Comment by godbout** [comment]
:D

how should we call them?

ScrollaDidStart/ScrollaDidStop?
feels like we should find something more creative.

**Comment by godbout** [comment]
ScrollaDidEngage
ScrollaDidDisengage

done.

**Comment by godbout** [comment]
in a2: https://github.com/godbout/Scrolla.docs/releases/tag/1.a2

please close if working fine!
